# Generated by Django 4.2.1 on 2023-06-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="content",
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name="posts",
            name="published_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
