# Generated by Django 4.2.1 on 2023-06-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0002_alter_posts_content_alter_posts_published_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="content",
            field=models.TextField(max_length=1000),
        ),
    ]
